apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo0723
  labels:
    app: devops-demo0723
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-demo0723
  template:
    metadata:
      labels:
        app: devops-demo0723
    spec:
      containers:
        - name: devops-demo0723
          image: ghcr.io/howard60510-netizen/devops-demo0723:d1f4b239a9566a402ea1e69a105dbe8d910f5110
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
